#!/bin/bash

chdir={{ django_dir }}
NAME="{{ django_project }}"                                                      # Name of the application
DJANGODIR={{ django_dir }} # Django project directory
SOCKFILE={{ django_dir }}/{{ django_project }}/run/gunicorn.sock  # socket
USER=root                                                             # the user to run as
GROUP=root                                                        # the group to run as
NUM_WORKERS=3 # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE={{ django_project }}.settings.production
DJANGO_WSGI_MODULE={{ django_project }}.wsgi # WSGI module name
DATABASE_URL=postgres://{{ dbuser }}:{{ dbpassword }}@localhost/{{ dbname }}
STATIC_ROOT={{ static_dir }}

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH
export STATIC_ROOT=$STATIC_ROOT
export DATABASE_URL=$DATABASE_URL

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec /usr/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
--name $NAME \
--workers $NUM_WORKERS \
--user=$USER --group=$GROUP \
--bind=unix:$SOCKFILE \
--log-level=debug \
--log-file=-
