pipeline {
    agent {
    // Equivalent to "docker build -f Dockerfile.build --build-arg version=1.0.2 ./build/
        dockerfile {
            filename 'Dockerfile'
            dir '01-docker/etcd/'
        }
    }
    stages {
        stage('build') {
            steps {
                sh 'etcd'
            }
        }
    }
}
