node {
    def app

    stage('Clone repository') {
        checkout scm
    }

    stage('Build image') {
        app = docker.build("fausst/etcd:${TAG}", "./01-docker/etcd")
    }

    stage('Test image') {
        app.inside {
            sh 'etcdctl version'
        }
    }

    stage('Push image') {
        docker.withRegistry('https://registry.hub.docker.com/fausst/etcd','my-docker-hub-credential') {
            app.push("${TAG}")
        }
    }
}
